name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. 设置 QEMU (如果你要构建 ARMv7 镜像，必须加这步)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置 Buildx
      - name: Set up Docker Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 构建并推送到 Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7  # 指定构建 ARMv7 架构
          push: true                # 设置为 true 才会推送到远程
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-pansou:latest
